select * from CHData 
where summary like '%military%' 
or summary like '%retired sergeant%' 
or summary like '%ex-US Air Force%' 
or summary like '%former Marine%' 
or summary like '%Army veteran%' 
or summary like '%Army Specialist' 
or summary like '%veteran of the Virginia Army%'
or summary like '%Off-duty sheriff''s deputy%'
or summary like '%Army psychiatrist%'
or summary like '%three-year stint in the US Army%'